import test from "node:test";
import assert from "node:assert/strict";
import { MAP_SLOTS, mapById } from "../src/config/map-config.js";
import { Partygoer, HypeMan, GrillMaster, CoolerCarrier, PartyDJ, PartyCoach, FirstAidVolunteer } from "../src/entities/block-party-enemies.js";
import { PartyPlannerBoss } from "../src/entities/party-planner-boss.js";

test("Neighborhood Block Party is a 1.7-screen support arena with a 100 enemy cap",()=>{const map=mapById("neighborhood-block-party");assert.equal(MAP_SLOTS.at(-2),map);assert.equal(map.world.width/1280,1.7);assert.equal(map.world.height/720,1.7);assert.equal(map.enemyCap,100);assert.equal(map.boss.health,38000);assert.equal(map.bossSpawnTime,120);assert.equal(Object.values(map.blockPartySpawnWeights).reduce((a,b)=>a+b,0),1);});

test("Block Party enemy health values and support identities match the design",()=>{const position={x:100,y:100};assert.equal(new Partygoer(position).health,800);assert.equal(new HypeMan(position).health,600);assert.equal(new GrillMaster(position).health,900);assert.equal(new CoolerCarrier(position).health,1000);assert.equal(new PartyDJ(position).health,700);assert.equal(new PartyCoach(position).health,750);assert.equal(new FirstAidVolunteer(position).health,650);});

test("same support auras are represented as one effect while different types combine",()=>{const target=new Partygoer({x:100,y:100});target.partyRallyAttackTime=2;const dj=new PartyDJ({x:100,y:100});const secondDJ=new PartyDJ({x:100,y:100});const cooler=new CoolerCarrier({x:100,y:100});const normals=[target,dj,secondDJ,cooler];target.partyAttackSpeedMultiplier=1+(target.partyRallyAttackTime>0?.25:0);for(const source of normals){if(source instanceof PartyDJ&&Math.hypot(target.x-source.x,target.y-source.y)<=source.auraRadius)target.partyAttackSpeedMultiplier=Math.max(target.partyAttackSpeedMultiplier,1.25+(target.partyRallyAttackTime>0?.25:0));if(source instanceof CoolerCarrier&&Math.hypot(target.x-source.x,target.y-source.y)<=source.auraRadius)target.partyDamageResistance=Math.max(target.partyDamageResistance??0,.25);}assert.equal(target.partyAttackSpeedMultiplier,1.5);assert.equal(target.partyDamageResistance,.25);});

test("Party Planner enters its intensified phase and emits support events",()=>{const map=mapById("neighborhood-block-party"),boss=new PartyPlannerBoss({x:400,y:300,config:map.boss,world:map.world});assert.equal(boss.name,"The Party Planner");boss.health=9999;boss.spawnTimer=0;boss.rallyTimer=0;boss.balloonTimer=0;boss.pizzaTimer=0;boss.confettiTimer=0;const events=boss.update(.01,{x:600,y:300},[],[]);assert.equal(events.perfectlyPlanned,true);assert.equal(events.spawnPartygoer,true);assert.equal(events.partyRally.duration,4);assert.equal(events.balloonShield.count,6);assert.equal(events.pizzaDelivery.count,7);assert.equal(events.confettiCannon.lanes,7);});
