import test from "node:test";
import assert from "node:assert/strict";
import { MAP_SLOTS, mapById } from "../src/config/map-config.js";
import { BagGremlin, CanStack, BaguetteBandit, FrozenDinner, CartGoblin, StoreManagerBoss } from "../src/entities/supermarket-enemies.js";

const world={width:1280,height:720};
test("Supermarket follows Neighborhood Block Party with its requested arena and solid aisles",()=>{const map=mapById("supermarket");assert.equal(MAP_SLOTS.at(-1),map);assert.equal(map.world.width/1280,1.8);assert.equal(map.world.height/720,1.6);assert.equal(map.enemyCap,100);assert.equal(map.boss.health,42000);assert.equal(Object.values(map.supermarketSpawnWeights).reduce((a,b)=>a+b,0),1);assert.equal(map.obstacles.length,3);assert.ok(map.obstacles.every(obstacle=>obstacle.kind==="supermarket-shelf"&&obstacle.solid));});
test("Supermarket enemies expose their requested health and staged mechanics",()=>{const o={x:100,y:100,world};assert.equal(new BagGremlin(o).health,900);const cans=new CanStack(o);assert.equal(cans.health,1100);assert.equal(cans.healthCans(),3);cans.health=800;assert.equal(cans.healthCans(),2);cans.health=200;assert.equal(cans.healthCans(),0);assert.equal(new BaguetteBandit(o).health,750);assert.equal(new FrozenDinner(o).health,1300);assert.equal(new CartGoblin(o).health,1000);});
test("Cart Goblins only approach carts and launch them at high speed",()=>{const goblin=new CartGoblin({x:100,y:100,world}),player={x:700,y:500};goblin.update(1,player);assert.deepEqual([goblin.x,goblin.y],[100,100]);goblin.cart={x:300,y:100,radius:30,rolling:false};goblin.cartTimer=10;goblin.update(1,player);assert.ok(goblin.x>100);goblin.x=260;goblin.cartTimer=0;goblin.update(.01,player);const event=goblin.update(.71,player);assert.ok(Math.hypot(event.launchCart.vx,event.launchCart.vy)>=819);});
test("Store Manager enters CLOSING TIME and increases every specified attack",()=>{const map=mapById("supermarket"),boss=new StoreManagerBoss({x:300,y:300,world:map.world,config:map.boss});boss.health=10999;boss.cartCall=0;boss.shelf=0;boss.cleanup=0;boss.price=0;const events=boss.update(.01,{x:600,y:300});assert.equal(events.closingTime,true);assert.equal(events.cartCall,5);assert.equal(events.shelfSweep,8);assert.equal(events.cleanupCrew.damage,70);assert.equal(events.priceCheck,4);assert.equal(boss.maxHealth,42000);});
