const supermarketClamp=(v,a,b)=>Math.max(a,Math.min(b,v));
class MarketEnemy{
  constructor(o){Object.assign(this,o);this.maxHealth=this.health;this.enemyType=this.type;this.hitFlash=0;this.freezeTime=0;this.slowTime=0;this.shield=0;}
  get active(){return this.health>0;}
  takeDamage(amount){let damage=Math.max(0,amount),blocked=Math.min(this.shield,damage);this.shield-=blocked;damage-=blocked;this.health=Math.max(0,this.health-damage);this.hitFlash=.12;return this.health===0;}
  tick(dt){this.hitFlash=Math.max(0,this.hitFlash-dt);this.freezeTime=Math.max(0,this.freezeTime-dt);this.slowTime=Math.max(0,this.slowTime-dt);}
  chase(dt,target,mult=1){const a=Math.atan2(target.y-this.y,target.x-this.x),slow=this.slowTime>0?.5:1;this.x=supermarketClamp(this.x+Math.cos(a)*this.speed*mult*slow*dt,this.radius,this.world.width-this.radius);this.y=supermarketClamp(this.y+Math.sin(a)*this.speed*mult*slow*dt,this.radius,this.world.height-this.radius);}
  bar(c){c.fillStyle="#171817";c.fillRect(-this.radius,-this.radius-13,this.radius*2,5);c.fillStyle="#ef725d";c.fillRect(-this.radius+1,-this.radius-12,(this.radius*2-2)*this.health/this.maxHealth,3);}
}
export class BagGremlin extends MarketEnemy{
  constructor({x,y,world}){super({x,y,world,health:900,speed:82,damage:18,radius:27,type:"bag-gremlin",coinValue:12,xpValue:70});this.hopTimer=3;this.hops=0;this.hopTime=0;}
  update(dt,t){this.tick(dt);if(this.hopTime>0){this.hopTime-=dt;this.x=supermarketClamp(this.x+this.vx*dt,this.radius,this.world.width-this.radius);this.y=supermarketClamp(this.y+this.vy*dt,this.radius,this.world.height-this.radius);if(this.hopTime<=0&&--this.hops>0)this.startHop(t);return{};}this.hopTimer-=dt;if(this.hopTimer<=0){this.hopTimer=4;this.hops=3;this.startHop(t);return{};}this.chase(dt,t);return{};}
  startHop(t){const a=Math.atan2(t.y-this.y,t.x-this.x)+(Math.random()-.5)*.5;this.vx=Math.cos(a)*310;this.vy=Math.sin(a)*310;this.hopTime=.28;}
  render(c,cam){c.save();const hop=this.hopTime>0?Math.sin(this.hopTime/.28*Math.PI)*18:0;c.translate(this.x-cam.x,this.y-cam.y-hop);c.fillStyle="rgba(20,18,15,.28)";c.beginPath();c.ellipse(0,30+hop*.35,27,7,0,0,Math.PI*2);c.fill();c.fillStyle="#5d3e25";c.fillRect(-25,-17,5,35);c.fillRect(20,-17,5,35);c.fillStyle=this.hitFlash?"#fff":"#b98a52";c.beginPath();c.moveTo(-22,-22);c.lineTo(-15,-29);c.lineTo(15,-29);c.lineTo(22,-22);c.lineTo(20,24);c.lineTo(-20,24);c.closePath();c.fill();c.fillStyle="#d8b078";c.fillRect(-16,-25,32,6);c.fillStyle="#725033";c.fillRect(-17,-15,34,4);c.fillRect(-17,14,34,4);c.fillStyle="#282019";c.fillRect(-12,-8,7,8);c.fillRect(5,-8,7,8);c.fillStyle="#f5e0ae";c.fillRect(-10,-6,3,3);c.fillRect(7,-6,3,3);c.fillStyle="#4a2c20";c.fillRect(-8,5,16,4);c.fillRect(-5,9,10,3);c.fillStyle="#e4bd4f";c.fillRect(-17,18,34,5);c.fillStyle="#604225";c.fillRect(-20,24,12,8);c.fillRect(8,24,12,8);c.fillStyle="#8d6034";c.fillRect(-13,-34,5,10);c.fillRect(8,-34,5,10);this.bar(c);c.restore();}
}
export class CanStack extends MarketEnemy{
  constructor({x,y,world}){super({x,y,world,health:1100,speed:43,damage:18,radius:26,type:"can-stack",coinValue:16,xpValue:90});this.attackTimer=5;this.firedCans=[];}
  healthCans(){return this.health>800?3:this.health>500?2:this.health>200?1:0;}
  availableCans(){return Math.max(0,this.healthCans()-this.firedCans.length);}
  update(dt,t){this.tick(dt);this.firedCans=this.firedCans.map(v=>v-dt).filter(v=>v>0);this.attackTimer-=dt;const cans=this.availableCans();if(cans&&this.attackTimer<=0){this.attackTimer=5;this.firedCans.push(8);return{throwCan:{x:t.x,y:t.y,speed:340,damage:28}};}this.chase(dt,t,this.health<=200?2.7:1);return{};}
  render(c,cam){c.save();c.translate(this.x-cam.x,this.y-cam.y);c.fillStyle="rgba(20,18,15,.25)";c.fillRect(-27,27,54,7);c.fillStyle=this.hitFlash?"#fff":"#66564a";c.fillRect(-25,7,50,21);c.fillStyle="#292522";c.fillRect(-18,12,8,7);c.fillRect(10,12,8,7);c.fillRect(-7,21,14,4);const colors=["#d95048","#e7b93d","#4b9fc4"];for(let i=0;i<this.availableCans();i++){const y=3-i*23;c.fillStyle="#d9d3c3";c.fillRect(-18,y-2,36,22);c.fillStyle=colors[i];c.fillRect(-16,y+1,32,16);c.fillStyle="rgba(255,255,255,.55)";c.fillRect(-13,y+3,5,12);c.fillStyle="#403a35";c.fillRect(-9,y+6,5,5);c.fillRect(5,y+6,5,5);c.fillRect(-5,y+13,10,3);}this.bar(c);c.restore();}
}
export class BaguetteBandit extends MarketEnemy{
  constructor({x,y,world}){super({x,y,world,health:750,speed:88,damage:18,radius:28,type:"baguette-bandit",coinValue:13,xpValue:75});this.thrustTimer=4;this.warning=0;this.thrust=0;}
  update(dt,t){this.tick(dt);if(this.thrust>0){this.thrust-=dt;this.x=supermarketClamp(this.x+this.vx*dt,this.radius,this.world.width-this.radius);this.y=supermarketClamp(this.y+this.vy*dt,this.radius,this.world.height-this.radius);return{};}if(this.warning>0){this.warning-=dt;if(this.warning<=0){const a=Math.atan2(this.ty-this.y,this.tx-this.x);this.vx=Math.cos(a)*410;this.vy=Math.sin(a)*410;this.thrust=.55;this.damage=45;return{baguetteThrust:{angle:a,length:170,width:24,damage:45,knockback:180}};}return{};}this.damage=18;this.thrustTimer-=dt;if(this.thrustTimer<=0){this.thrustTimer=4;this.warning=.6;this.tx=t.x;this.ty=t.y;}else this.chase(dt,t);return{};}
  render(c,cam){c.save();c.translate(this.x-cam.x,this.y-cam.y);const a=this.thrust>0?Math.atan2(this.vy,this.vx):0;c.fillStyle="rgba(20,18,15,.25)";c.fillRect(-23,27,48,7);c.fillStyle=this.hitFlash?"#fff":"#824a35";c.fillRect(-20,-14,38,39);c.fillStyle="#d9aa7c";c.fillRect(-14,-28,26,18);c.fillStyle="#31211b";c.fillRect(-9,-22,5,5);c.fillRect(4,-22,5,5);c.fillStyle="#4a2c22";c.fillRect(-16,25,12,7);c.fillRect(6,25,12,7);c.save();c.rotate(a);c.fillStyle="#d99d50";c.fillRect(2,-7,78,14);c.fillStyle="#f3cb7b";c.fillRect(10,-5,67,10);c.fillStyle="#9b672f";for(let x=18;x<69;x+=15)c.fillRect(x,-5,4,4);c.fillStyle="#f4db9b";c.fillRect(75,-4,16,8);c.restore();this.bar(c);c.restore();}
}
export class FrozenDinner extends MarketEnemy{
  constructor({x,y,world}){super({x,y,world,health:1300,speed:42,damage:20,radius:31,type:"frozen-dinner",coinValue:20,xpValue:115});this.throwTimer=6;}
  update(dt,t){this.tick(dt);this.throwTimer-=dt;if(this.throwTimer<=0){this.throwTimer=6;return{frozenPackage:{x:t.x,y:t.y,speed:520,damage:36}};}this.chase(dt,t);return{};}
  render(c,cam){c.save();c.translate(this.x-cam.x,this.y-cam.y);c.fillStyle="rgba(20,18,15,.25)";c.fillRect(-34,28,68,7);c.fillStyle=this.hitFlash?"#fff":"#56a9c9";c.fillRect(-31,-26,62,55);c.fillStyle="#d9f1f4";c.fillRect(-25,-20,50,27);c.fillStyle="#7ec9dd";c.fillRect(-21,-16,42,19);c.fillStyle="#eef9f8";c.fillRect(-15,-12,12,9);c.fillStyle="#2b5364";c.fillRect(1,-12,15,4);c.fillRect(1,-5,11,4);c.fillStyle="#224959";c.fillRect(-18,12,36,10);c.fillStyle="#d9ecf0";c.fillRect(-14,15,28,4);c.fillStyle="#315b69";c.fillRect(-23,28,15,6);c.fillRect(8,28,15,6);this.bar(c);c.restore();}
}
export class CartGoblin extends MarketEnemy{
  constructor({x,y,world}){super({x,y,world,health:1000,speed:65,damage:16,radius:28,type:"cart-goblin",coinValue:20,xpValue:110});this.cartTimer=2;this.warning=0;this.cart=null;}
  update(dt,t){this.tick(dt);this.cartTimer-=dt;if(this.cart?.rolling)this.cart=null;if(!this.cart){this.vx=0;this.vy=0;return{seekCart:true};}if(this.warning>0){this.warning-=dt;if(this.warning<=0){const a=Math.atan2(this.ty-this.cart.y,this.tx-this.cart.x);return{launchCart:{cart:this.cart,vx:Math.cos(a)*820,vy:Math.sin(a)*820}};}return{};}if(this.cartTimer<=0){this.cartTimer=7;this.warning=.7;this.tx=t.x;this.ty=t.y;return{cartWarning:{cart:this.cart,lifetime:.7}};}const a=Math.atan2(this.cart.y-this.y,this.cart.x-this.x),distance=Math.hypot(this.cart.x-this.x,this.cart.y-this.y);if(distance>this.radius+this.cart.radius){this.x=supermarketClamp(this.x+Math.cos(a)*this.speed*dt,this.radius,this.world.width-this.radius);this.y=supermarketClamp(this.y+Math.sin(a)*this.speed*dt,this.radius,this.world.height-this.radius);}return{};}
  render(c,cam){c.save();c.translate(this.x-cam.x,this.y-cam.y);c.fillStyle="rgba(20,18,15,.25)";c.fillRect(-27,27,54,7);c.fillStyle=this.hitFlash?"#fff":"#4f9658";c.fillRect(-23,-18,46,43);c.fillStyle="#75b56f";c.fillRect(-17,-28,34,18);c.fillStyle="#214329";c.fillRect(-12,-20,7,7);c.fillRect(6,-20,7,7);c.fillRect(-6,-7,14,6);c.fillStyle="#b83e35";c.fillRect(-4,-5,9,3);c.fillStyle="#324038";c.fillRect(-26,2,8,23);c.fillRect(18,2,8,23);c.fillStyle="#262b28";c.fillRect(-19,25,13,7);c.fillRect(7,25,13,7);if(this.cart){c.strokeStyle="#9ca9a8";c.lineWidth=4;c.beginPath();c.moveTo(22,3);c.lineTo(35,15);c.stroke();}this.bar(c);c.restore();}
}
export class StoreManagerBoss extends MarketEnemy{
  constructor({x,y,world,config}){super({x,y,world,health:config.health,speed:config.speed,damage:config.damage,radius:67,type:"store-manager",coinValue:0,xpValue:0});this.name=config.name;this.isBoss=true;this.cartCall=6;this.shelf=5;this.cleanup=8;this.price=10;this.closing=false;}
  update(dt,t){this.tick(dt);const e={};if(!this.closing&&this.health<11000){this.closing=true;e.closingTime=true;}this.chase(dt,t,this.closing?1.2:1);this.cartCall-=dt;this.shelf-=dt;this.cleanup-=dt;this.price-=dt;if(this.cartCall<=0){this.cartCall=6;e.cartCall=this.closing?5:3;}if(this.shelf<=0){this.shelf=5;e.shelfSweep=this.closing?8:6;}if(this.cleanup<=0){this.cleanup=this.closing?6:8;e.cleanupCrew={radius:220,damage:70,knockback:240,angle:Math.atan2(t.y-this.y,t.x-this.x)};}if(this.price<=0){this.price=10;e.priceCheck=this.closing?4:3;}return e;}
  render(c,cam){c.save();c.translate(this.x-cam.x,this.y-cam.y);if(this.closing){c.strokeStyle="#ff493f";c.lineWidth=7;c.beginPath();c.arc(0,0,82+Math.sin(Date.now()/80)*5,0,Math.PI*2);c.stroke();}c.fillStyle="#334b62";c.fillRect(-56,-18,112,54);c.fillStyle="#17191b";c.fillRect(-48,28,25,16);c.fillRect(23,28,25,16);c.fillStyle=this.hitFlash?"#fff":"#d9b18d";c.beginPath();c.arc(0,-31,26,0,Math.PI*2);c.fill();c.fillStyle="#f3d94e";c.fillRect(-30,-4,60,18);c.fillStyle="#151515";c.fillRect(-76,-92,152,8);c.fillStyle="#ef5c4e";c.fillRect(-73,-90,146*this.health/this.maxHealth,4);c.restore();}
}
