export const ENEMY_GLOSSARY = Object.freeze([
  Object.freeze({ id: "gnome", name: "Lawn Gnome", description: "A fast garden invader that deals 6 contact damage." }),
  Object.freeze({ id: "gopher", name: "Gopher", description: "A durable burrower that resurfaces at full health." }),
  Object.freeze({ id: "king-gnomulus", name: "King Gnomulus", description: "The Backyard boss who summons and throws gnomes." }),
  Object.freeze({ id: "common-weed", name: "Common Weed", description: "A short-lived plant that grows two children toward the player." }),
  Object.freeze({ id: "strongweed", name: "Strongweed", description: "A Dandelion-forged weed with 150 HP that does not expire or reproduce during the boss fight." }),
  Object.freeze({ id: "squirrel", name: "Squirrel", description: "A very fast park pest that bursts toward the player and sometimes jumps sideways. 80 HP, 10 XP, 1 coin." }),
  Object.freeze({ id: "acorn-squirrel", name: "Acorn Squirrel", description: "A cautious squirrel that keeps its distance, throws acorns at your last position, then repositions. 120 HP." }),
  Object.freeze({ id: "dandelion", name: "Dandelion", description: "The Community Garden boss; its spores grow weeds and its low-health shield absorbs damage." }),
  Object.freeze({ id: "lily-queen", name: "Lily Queen", description: "A stationary Aquatic Garden boss with 5,000 HP, a regenerating shield, and relentless riverbank weed growth." }),
  Object.freeze({ id: "groundskeeper", name: "The Groundskeeper", description: "The Public Park boss on a ride-on mower. Charges across the arena, destroys obstacles, fires grass clippings, and releases both squirrel variants." }),
  Object.freeze({ id: "goose", name: "Goose", description: "A 40-health lake pest that charges quickly at 250 speed. Drops 1 coin and 10 XP." }),
  Object.freeze({ id: "pondfather", name: "The Pondfather", description: "A gigantic goose that alternates between the lake and land, divebombing and spawning geese." }),
  Object.freeze({ id: "golfer", name: "Golfer", description: "A 300-health golfer that pauses at range to fire quick 8-damage balls, but charges with its club when approached." }),
  Object.freeze({ id: "pro-golfer", name: "The Pro Golfer", description: "The Golf Course boss who retreats quickly and alternates regular balls, fan shots, and bunker bombs." }),
  Object.freeze({ id: "snail", name: "Snail", description: "A slow 400-health forest crawler that leaves slime trails which fade after five seconds." }),
  Object.freeze({ id: "mosquito", name: "Mosquito", description: "A fast flying 50-health pest that ignores trees and periodically dashes." }),
  Object.freeze({ id: "deer", name: "Deer", description: "A 500-health forest enemy that warns before charging in a straight line." }),
  Object.freeze({ id: "ancient-snail", name: "The Ancient Snail", description: "A huge Redwood Trail boss with permanent slime, spit projectiles, shell slams, and snail reinforcements." }),
  Object.freeze({ id: "rogue-soccer-ball", name: "Rogue Soccer Ball", description: "A 200-health rolling ball that accelerates toward you, passes by, and turns around for another approach." }),
  Object.freeze({ id: "sprinter", name: "Sprinter", description: "A 200-health runner that sprints for three seconds, then becomes visibly exhausted for one second." }),
  Object.freeze({ id: "backpack", name: "Angry Backpack", description: "A hopping 550-health tank that occasionally falls over before standing up again." }),
  Object.freeze({ id: "basketball", name: "Basketball", description: "A 100-health bouncing ball whose contact damage is most dangerous when it is near the ground." }),
  Object.freeze({ id: "pe-teacher", name: "The PE Teacher", description: "An 8,000-health School Field boss with dodgeballs, whistle shockwaves, and rapid track laps." }),
  Object.freeze({ id: "ball-launcher", name: "The Ball Launcher", description: "A stationary 10,000-health machine that fires mixed sports balls and radial ball dumps." }),
  Object.freeze({ id: "construction-worker", name: "Construction Worker", description: "A durable 500-health hammer carrier that steadily pursues the player." }),
  Object.freeze({ id: "traffic-cone", name: "Traffic Cone", description: "A hopping support unit that plants itself and speeds nearby enemies up by 25%." }),
  Object.freeze({ id: "runaway-tire", name: "Runaway Tire", description: "A fast rolling enemy that ricochets from the arena boundary up to three times." }),
  Object.freeze({ id: "brick-carrier", name: "Brick Carrier", description: "An 800-health carrier whose thrown and dropped bricks cause damaging explosions." }),
  Object.freeze({ id: "safety-vest", name: "Safety Vest", description: "A support enemy that attaches to allies and grants a temporary 100-HP shield." }),
  Object.freeze({ id: "excavator", name: "The Excavator", description: "The Construction Site boss; its bucket, dirt, debris, and summoned crew reshape the fight." }),
  Object.freeze({ id: "chicken", name: "Chicken", description: "A 150-health zigzagging farm enemy that periodically sprints and has a 50% chance to leave an Egg." }),
  Object.freeze({ id: "chicken-egg", name: "Egg", description: "A rolling 100-health Egg that hatches into three Chicks after ten seconds if it survives." }),
  Object.freeze({ id: "chick", name: "Chick", description: "A small fast enemy that grows into a Chicken after surviving for twenty seconds." }),
  Object.freeze({ id: "rooster", name: "Rooster", description: "A durable farm support enemy whose crow speeds nearby Chickens and Chicks for three seconds." }),
  Object.freeze({ id: "mother-hen", name: "Mother Hen", description: "The oversized Chicken Farm boss with Egg Toss, Chicken Rush, Wing Blast, and an enraged phase." }),
]);
