export const ENEMY_GLOSSARY = Object.freeze([
  Object.freeze({ id: "gnome", name: "Lawn Gnome", description: "A fast garden invader that deals 6 contact damage." }),
  Object.freeze({ id: "gopher", name: "Gopher", description: "A durable burrower that resurfaces at full health." }),
  Object.freeze({ id: "king-gnomulus", name: "King Gnomulus", description: "A heavily armored gnome king who summons formations and throws minions toward your snapshotted position." }),
  Object.freeze({ id: "common-weed", name: "Common Weed", description: "A short-lived plant that grows two children toward the player." }),
  Object.freeze({ id: "strongweed", name: "Strongweed", description: "A sturdy 150-health weed created by special enemies or terrain. It does not reproduce or expire, slowly drifts toward you, and pushes away from nearby weeds." }),
  Object.freeze({ id: "squirrel", name: "Squirrel", description: "A very fast pest that bursts toward you and occasionally jumps sideways to evade ranged attacks. 80 HP, 20 XP, and 2 coins." }),
  Object.freeze({ id: "acorn-squirrel", name: "Acorn Squirrel", description: "A cautious ranged enemy that keeps its distance, throws an acorn at your snapshotted position, then quickly repositions before attacking again. 120 HP." }),
  Object.freeze({ id: "dandelion", name: "Dandelion", description: "A regenerating plant boss that fires spores, creates weeds, and raises a limited 200-point shield when its health becomes low." }),
  Object.freeze({ id: "lily-queen", name: "Lily Queen", description: "A stationary Aquatic Garden boss with 5,000 HP, a regenerating shield, and relentless riverbank weed growth." }),
  Object.freeze({ id: "groundskeeper", name: "The Groundskeeper", description: "A fast boss on a ride-on mower that lines up charging runs and fires grass clippings. Some versions can crush obstacles and release squirrels." }),
  Object.freeze({ id: "goose", name: "Goose", description: "A 40-health enemy that rapidly charges toward you at 250 speed. Drops 1 coin and 10 XP." }),
  Object.freeze({ id: "pondfather", name: "The Pondfather", description: "A gigantic goose that alternates between the lake and land, divebombing and spawning geese." }),
  Object.freeze({ id: "golfer", name: "Golfer", description: "A 300-health golfer that pauses at range to fire quick 8-damage balls, but charges with its club when approached." }),
  Object.freeze({ id: "pro-golfer", name: "The Pro Golfer", description: "The Golf Course boss who retreats quickly and alternates regular balls, fan shots, and bunker bombs." }),
  Object.freeze({ id: "snail", name: "Snail", description: "A slow 400-health forest crawler that leaves slime trails which fade after five seconds." }),
  Object.freeze({ id: "mosquito", name: "Mosquito", description: "A fast flying 50-health pest that ignores trees and periodically dashes." }),
  Object.freeze({ id: "deer", name: "Deer", description: "A 500-health forest enemy that warns before charging in a straight line." }),
  Object.freeze({ id: "ancient-snail", name: "The Ancient Snail", description: "A huge Redwood Trail boss with permanent slime, spit projectiles, shell slams, and snail reinforcements." }),
  Object.freeze({ id: "rogue-soccer-ball", name: "Rogue Soccer Ball", description: "A 200-health rolling ball that accelerates toward you, passes by, and turns around for another approach." }),
  Object.freeze({ id: "sprinter", name: "Sprinter", description: "A 200-health runner that sprints for three seconds, then becomes visibly exhausted for one second." }),
  Object.freeze({ id: "backpack", name: "Angry Backpack", description: "A hopping 550-health tank that occasionally falls over before standing up again." }),
  Object.freeze({ id: "basketball", name: "Basketball", description: "A 100-health bouncing ball whose contact damage is most dangerous when it is near the ground." }),
  Object.freeze({ id: "pe-teacher", name: "The PE Teacher", description: "An 8,000-health School Field boss with dodgeballs, whistle shockwaves, and rapid track laps." }),
  Object.freeze({ id: "ball-launcher", name: "The Ball Launcher", description: "A stationary 10,000-health machine that fires mixed sports balls and radial ball dumps." }),
  Object.freeze({ id: "construction-worker", name: "Construction Worker", description: "A durable 500-health hammer carrier that steadily pursues the player." }),
  Object.freeze({ id: "traffic-cone", name: "Traffic Cone", description: "A hopping support unit that plants itself and speeds nearby enemies up by 25%." }),
  Object.freeze({ id: "runaway-tire", name: "Runaway Tire", description: "A fast rolling enemy that ricochets from the arena boundary up to three times." }),
  Object.freeze({ id: "brick-carrier", name: "Brick Carrier", description: "An 800-health carrier whose thrown and dropped bricks cause damaging explosions." }),
  Object.freeze({ id: "safety-vest", name: "Safety Vest", description: "A support enemy that attaches to allies and grants a temporary 100-HP shield." }),
  Object.freeze({ id: "excavator", name: "The Excavator", description: "The Construction Site boss; its bucket, dirt, debris, and summoned crew reshape the fight." }),
  Object.freeze({ id: "chicken", name: "Chicken", description: "A 150-health zigzagging farm enemy that periodically sprints and has a 50% chance to leave an Egg." }),
  Object.freeze({ id: "chicken-egg", name: "Egg", description: "A rolling 100-health Egg that hatches into three Chicks after ten seconds if it survives." }),
  Object.freeze({ id: "chick", name: "Chick", description: "A small fast enemy that grows into a Chicken after surviving for twenty seconds." }),
  Object.freeze({ id: "rooster", name: "Rooster", description: "A durable farm support enemy whose crow speeds nearby Chickens and Chicks for three seconds." }),
  Object.freeze({ id: "mother-hen", name: "Mother Hen", description: "The oversized Chicken Farm boss with Egg Toss, Chicken Rush, Wing Blast, and an enraged phase." }),
  Object.freeze({ id: "angry-corn", name: "Angry Corn", description: "A 350-health crop that stops every four seconds and fires a fan of three kernels." }),
  Object.freeze({ id: "popcorn", name: "Popcorn", description: "A fast 100-health enemy that bursts into a damaging, high-knockback blast when defeated." }),
  Object.freeze({ id: "mini-tractor", name: "Mini Tractor", description: "A rare 1,000-health charger that harvests crop rows and clears space as it drives." }),
  Object.freeze({ id: "combine", name: "The Combine", description: "The Corn Farm boss. It harvests rows, fires kernel fans, dumps Popcorn piles, and enters overdrive below 5,000 HP." }),
  Object.freeze({ id: "cactus", name: "Cactus", description: "A durable 700-health plant that stops every four seconds and fires eight fast needles radially." }),
  Object.freeze({ id: "snapflower", name: "Snapflower", description: "An aggressive flower that warns before lunging toward a snapshotted position." }),
  Object.freeze({ id: "sunflower", name: "Sunflower", description: "A 500-health support flower whose yellow aura heals nearby normal enemies." }),
  Object.freeze({ id: "vine", name: "Vine", description: "A terrain-control plant that grows temporary slowing vines toward the player's last position." }),
  Object.freeze({ id: "queen-rose", name: "Queen Rose", description: "The stationary 20,000-health Botanical Garden boss. Overlapping thorns, petals, sweeping vines, and pollen become stronger in Full Bloom." }),
  Object.freeze({ id: "crab", name: "Crab", description: "A 500-health water-immune beach enemy that closes in through erratic sideways bursts." }),
  Object.freeze({ id: "hermit-crab", name: "Hermit Crab", description: "A 1,200-health tank that hides for two seconds and gains 75% armor inside its shell." }),
  Object.freeze({ id: "beach-ball-enemy", name: "Beach Ball", description: "A fast 300-health bouncing enemy that accelerates at walls and delivers powerful knockback." }),
  Object.freeze({ id: "sand-octopus", name: "Sand Octopus", description: "A durable 1,500-health stationary ambusher that marks reachable sand before bursting a tentacle from it." }),
  Object.freeze({ id: "lifeguard", name: "Lifeguard", description: "A beach support enemy that pulls allies to safety and grants them a temporary 100-HP shield." }),
  Object.freeze({ id: "king-crab", name: "King Crab", description: "The 25,000-health Beach boss. Its claw slams, tidal charges, and bubble barrages become fiercer at high tide and low health." }),
  Object.freeze({ id:"raccoon",name:"Raccoon",description:"A 650-health scavenger that scampers unpredictably and moves 20% faster in darkness." }),
  Object.freeze({ id:"skunk",name:"Skunk",description:"A 500-health area-control enemy that leaves damaging three-second gas clouds." }),
  Object.freeze({ id:"camp-bear",name:"Bear",description:"A rare 2,000-health tank that roars before a locked, high-knockback charge." }),
  Object.freeze({ id:"camp-owl",name:"Owl",description:"A rare flying enemy that circles from afar and dives through snapshotted positions." }),
  Object.freeze({ id:"campground-ranger",name:"Campground Ranger",description:"The 28,000-health Campground boss. Searchlights, rolling logs, scattered campfires, and backpack junk enforce CAMPGROUND CLOSED!" }),
  Object.freeze({ id:"mountain-goat",name:"Mountain Goat",description:"A rare 1,600-health climber that pursues you, warns before locking onto your position, then charges straight ahead. Crashing into the arena boundary leaves it stunned and vulnerable." }),
  Object.freeze({ id:"mountain-eagle",name:"Mountain Eagle",description:"A rare 1,400-health flying hunter that ignores ground obstacles, circles at a distance, then dives through your snapshotted position and drops a warning-marked rock." }),
  Object.freeze({ id:"mountain-ram",name:"Mountain Ram",description:"A very rare 3,600-health tank. Its long warning locks in a devastating straight charge that causes heavy contact damage and can smash through other normal enemies." }),
  Object.freeze({ id:"billy-mountain-king",name:"Billy the Mountain King",description:"The 32,000-health Mountain Trail boss. Billy chains charges with rolling boulders, damages his own minions, and becomes more dangerous below 8,000 health." }),
  Object.freeze({ id:"partygoer",name:"Partygoer",description:"An unpredictable 800-health guest that weaves through the crowd while chasing the player." }),
  Object.freeze({ id:"hype-man",name:"Hype Man",description:"A 600-health support enemy whose shout gives nearby allies 35% extra movement speed for three seconds." }),
  Object.freeze({ id:"grill-master",name:"Grill Master",description:"A 900-health cook who serves visible food to heal the three most injured nearby allies by 150 health every six seconds." }),
  Object.freeze({ id:"cooler-carrier",name:"Cooler Carrier",description:"A slow 1,000-health defender. Its cool aura gives nearby normal enemies 25% damage resistance, but cannot protect other Cooler Carriers or stack with itself." }),
  Object.freeze({ id:"party-dj",name:"DJ",description:"A stationary 700-health support enemy whose pulsing music aura makes nearby enemies use abilities 25% faster. Multiple DJ auras do not stack." }),
  Object.freeze({ id:"party-coach",name:"Coach",description:"A 750-health coordinator who whistles every seven seconds, making up to five nearby enemies dash toward the player." }),
  Object.freeze({ id:"first-aid-volunteer",name:"First-Aid Volunteer",description:"A rare 650-health medic who grants the lowest-health nearby ally a temporary 400-point shield every eight seconds." }),
  Object.freeze({ id:"party-planner",name:"The Party Planner",description:"The 38,000-health Neighborhood Block Party boss. Rallying guests, balloon shields, pizza healing, confetti lanes, and support overloads intensify below 10,000 health." }),
  Object.freeze({id:"bag-gremlin",name:"Bag Gremlin",description:"A 900-health supermarket pest that interrupts its pursuit with three fast, direction-locked hops."}),
  Object.freeze({id:"can-stack",name:"Can Stack",description:"An 1,100-health stack of three throwable cans on a fast 200-health base. Damaged cans are lost permanently, while fired cans regenerate."}),
  Object.freeze({id:"baguette-bandit",name:"Baguette Bandit",description:"A 750-health attacker that locks its aim before making a long, narrow, high-knockback baguette thrust."}),
  Object.freeze({id:"frozen-dinner",name:"Frozen Dinner",description:"A rare 1,300-health ranged enemy whose packages slide through enemies and briefly freeze everything they hit."}),
  Object.freeze({id:"cart-goblin",name:"Cart Goblin",description:"A rare 1,000-health goblin that finds stopped shopping carts, warns, then launches them toward your snapshotted position."}),
  Object.freeze({id:"store-manager",name:"The Store Manager",description:"The 42,000-health Supermarket boss. Cart calls, shelf sweeps, mop attacks, and falling price-check crates accelerate during CLOSING TIME."}),
]);
