import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceFiles = [
  "src/config/game-config.js",
  "src/config/map-config.js",
  "src/config/glossary-config.js",
  "src/config/weapons.js",
  "src/config/economy-config.js",
  "src/systems/combat.js",
  "src/systems/progression.js",
  "src/systems/daily-quests.js",
  "src/systems/season.js",
  "src/systems/cloud-save.js",
  "src/systems/weapon-value.js",
  "src/systems/trading-post.js",
  "src/systems/economy.js",
  "src/core/camera.js",
  "src/core/input.js",
  "src/entities/held-weapon.js",
  "src/entities/player.js",
  "src/entities/gnome.js",
  "src/entities/gopher.js",
  "src/entities/snail.js",
  "src/entities/mosquito.js",
  "src/entities/deer.js",
  "src/entities/common-weed.js",
  "src/entities/squirrel.js",
  "src/entities/goose.js",
  "src/entities/acorn-squirrel.js",
  "src/entities/boss.js",
  "src/entities/dandelion-boss.js",
  "src/entities/lily-pad.js",
  "src/entities/lily-queen-boss.js",
  "src/entities/groundskeeper-boss.js",
  "src/entities/pondfather-boss.js",
  "src/entities/thrown-gnome.js",
  "src/entities/spore-projectile.js",
  "src/entities/acorn-projectile.js",
  "src/entities/grass-clipping.js",
  "src/entities/golf-ball-projectile.js",
  "src/entities/golf-bomb-projectile.js",
  "src/entities/golfer.js",
  "src/entities/pro-golfer-boss.js",
  "src/entities/ancient-snail-boss.js",
  "src/entities/snail-spit-projectile.js",
  "src/entities/school-field-enemies.js",
  "src/entities/school-ball-projectile.js",
  "src/entities/pe-teacher-boss.js",
  "src/entities/ball-launcher-boss.js",
  "src/entities/construction-enemies.js",
  "src/entities/excavator-boss.js",
  "src/entities/chicken-farm-enemies.js",
  "src/entities/mother-hen-boss.js",
  "src/entities/corn-farm-enemies.js",
  "src/entities/corn-kernel-projectile.js",
  "src/entities/combine-boss.js",
  "src/entities/projectile.js",
  "src/entities/pickup.js",
  "src/core/game.js",
  "src/main.js",
];

// The browser build is intentionally dependency-free and concatenates source
// files in a controlled order. Fail loudly when a newly imported local module
// is missing from that list instead of producing a bundle that crashes only
// when the new feature is first used.
const bundledFiles = new Set(sourceFiles);
for (const relativePath of sourceFiles) {
  const source = await readFile(path.join(projectRoot, relativePath), "utf8");
  const importPattern = /from\s+["'](\.{1,2}\/[^"']+)["']/g;
  for (const match of source.matchAll(importPattern)) {
    const importedPath = path.relative(
      projectRoot,
      path.resolve(projectRoot, path.dirname(relativePath), match[1]),
    );
    if (!bundledFiles.has(importedPath)) {
      throw new Error(`${relativePath} imports ${importedPath}, but it is missing from the browser bundle source list.`);
    }
  }
}

const sourceParts = await Promise.all(
  sourceFiles.map(async (relativePath) => {
    const source = await readFile(path.join(projectRoot, relativePath), "utf8");
    return source
      .replace(/^import .*;\n/gm, "")
      .replace(/^export /gm, "");
  }),
);

const bundle = [
  "// Generated by npm run build. Edit files in src/, not this bundle.",
  "(() => {",
  '  "use strict";',
  indent(sourceParts.join("\n\n"), 2),
  "})();",
  "",
].join("\n");

await writeFile(path.join(projectRoot, "game.bundle.js"), bundle);
console.log("Built game.bundle.js");

function indent(value, spaces) {
  const prefix = " ".repeat(spaces);
  return value
    .split("\n")
    .map((line) => (line ? `${prefix}${line}` : line))
    .join("\n");
}
