import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceFiles = [
  "src/config/game-config.js",
  "src/config/map-config.js",
  "src/config/glossary-config.js",
  "src/config/weapons.js",
  "src/config/economy-config.js",
  "src/systems/combat.js",
  "src/systems/progression.js",
  "src/systems/economy.js",
  "src/core/camera.js",
  "src/core/input.js",
  "src/entities/player.js",
  "src/entities/gnome.js",
  "src/entities/gopher.js",
  "src/entities/common-weed.js",
  "src/entities/boss.js",
  "src/entities/dandelion-boss.js",
  "src/entities/thrown-gnome.js",
  "src/entities/spore-projectile.js",
  "src/entities/projectile.js",
  "src/entities/pickup.js",
  "src/core/game.js",
  "src/main.js",
];

const sourceParts = await Promise.all(
  sourceFiles.map(async (relativePath) => {
    const source = await readFile(path.join(projectRoot, relativePath), "utf8");
    return source
      .replace(/^import .*;\n/gm, "")
      .replace(/^export /gm, "");
  }),
);

const bundle = [
  "// Generated by npm run build. Edit files in src/, not this bundle.",
  "(() => {",
  '  "use strict";',
  indent(sourceParts.join("\n\n"), 2),
  "})();",
  "",
].join("\n");

await writeFile(path.join(projectRoot, "game.bundle.js"), bundle);
console.log("Built game.bundle.js");

function indent(value, spaces) {
  const prefix = " ".repeat(spaces);
  return value
    .split("\n")
    .map((line) => (line ? `${prefix}${line}` : line))
    .join("\n");
}
