import { access, readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const indexPath = resolve(root, "index.html");
const html = await readFile(indexPath, "utf8");
const references = [...html.matchAll(/(?:src|href)="([^"]+)"/g)].map((match) => match[1]);

const errors = [];

for (const reference of references) {
  if (/^(?:https?:|#|data:|mailto:)/.test(reference)) continue;
  if (reference.startsWith("/")) {
    errors.push(`Root-absolute path will break under a project Pages URL: ${reference}`);
    continue;
  }

  const localPath = reference.split(/[?#]/, 1)[0];
  try {
    await access(resolve(root, localPath));
  } catch {
    errors.push(`Missing local asset referenced by index.html: ${reference}`);
  }
}

const bundle = await readFile(resolve(root, "game.bundle.js"), "utf8");
if (!bundle.startsWith("// Generated by npm run build.")) {
  errors.push("game.bundle.js is missing its generated bundle marker");
}
for (const requiredClass of ["CommonWeed", "DandelionBoss", "SporeProjectile"]) {
  if (!bundle.includes(`class ${requiredClass}`)) {
    errors.push(`game.bundle.js is missing the ${requiredClass} browser module`);
  }
}

if (errors.length > 0) {
  console.error(errors.join("\n"));
  process.exitCode = 1;
} else {
  console.log(`Release validation passed (${references.length} page references checked).`);
}
